// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/python.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -483502413;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'dpython',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateApiPythonPyModuleWrapperAsStr({required PyModuleWrapper that});

  String crateApiPythonPyModuleWrapperCallFunction(
      {required PyModuleWrapper that, required String funcName});

  String crateApiPythonPyModuleWrapperCallFunctionArgs(
      {required PyModuleWrapper that,
      required String funcName,
      required List<PyArgument> args});

  PyModuleWrapper crateApiPythonPyModuleWrapperImportModule(
      {required String moduleName});

  bool crateApiPythonPyObjectWrapperAsBool({required PyObjectWrapper that});

  double crateApiPythonPyObjectWrapperAsFloat({required PyObjectWrapper that});

  PlatformInt64 crateApiPythonPyObjectWrapperAsInt(
      {required PyObjectWrapper that});

  Future<List<String>> crateApiPythonPyObjectWrapperAsListString(
      {required PyObjectWrapper that});

  String crateApiPythonPyObjectWrapperAsRepr({required PyObjectWrapper that});

  String crateApiPythonPyObjectWrapperAsStr({required PyObjectWrapper that});

  Future<PyObjectWrapper> crateApiPythonPyObjectWrapperCall(
      {required PyObjectWrapper that, required List<PyArgument> args});

  Future<PyObjectWrapper> crateApiPythonPyObjectWrapperCallMethod(
      {required PyObjectWrapper that,
      required String methodName,
      required List<PyArgument> args});

  PyObjectWrapper crateApiPythonPyObjectWrapperGetItem(
      {required PyObjectWrapper that, required PyArgument key});

  PyObjectWrapper crateApiPythonPyObjectWrapperGetattr(
      {required PyObjectWrapper that, required String attrName});

  bool crateApiPythonPyObjectWrapperHasattr(
      {required PyObjectWrapper that, required String attrName});

  bool crateApiPythonPyObjectWrapperIsCallable({required PyObjectWrapper that});

  bool crateApiPythonPyObjectWrapperIsEmpty({required PyObjectWrapper that});

  bool crateApiPythonPyObjectWrapperIsNone({required PyObjectWrapper that});

  BigInt crateApiPythonPyObjectWrapperLen({required PyObjectWrapper that});

  void crateApiPythonPyObjectWrapperSetItem(
      {required PyObjectWrapper that,
      required PyArgument key,
      required PyArgument value});

  void crateApiPythonPyObjectWrapperSetattr(
      {required PyObjectWrapper that,
      required String attrName,
      required PyArgument value});

  void crateApiPythonInitPyEnv(
      {required String pythonHome,
      required String libPath,
      required String sitePackages});

  Future<String> crateApiPythonPythonUtilityEval(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals,
      required List<String> imports});

  Future<PyObjectWrapper> crateApiPythonPythonUtilityEvalAsObject(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals});

  Future<void> crateApiPythonPythonUtilityExecute(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals});

  Future<String> crateApiPythonPythonUtilityGetModuleAttr(
      {required String moduleName, required String attrName});

  Future<void> crateApiPythonPythonUtilityRunFile({required String filePath});

  Future<void> crateApiPythonPythonUtilitySetModuleAttr(
      {required String moduleName,
      required String attrName,
      required PyArgument value});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_PyModuleWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_PyModuleWrapper;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PyModuleWrapperPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_PyObjectWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_PyObjectWrapper;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PyObjectWrapperPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiPythonPyModuleWrapperAsStr({required PyModuleWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPythonPyModuleWrapperAsStrConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyModuleWrapperAsStrConstMeta =>
      const TaskConstMeta(
        debugName: "PyModuleWrapper_as_str",
        argNames: ["that"],
      );

  @override
  String crateApiPythonPyModuleWrapperCallFunction(
      {required PyModuleWrapper that, required String funcName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
            that, serializer);
        sse_encode_String(funcName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyModuleWrapperCallFunctionConstMeta,
      argValues: [that, funcName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyModuleWrapperCallFunctionConstMeta =>
      const TaskConstMeta(
        debugName: "PyModuleWrapper_call_function",
        argNames: ["that", "funcName"],
      );

  @override
  String crateApiPythonPyModuleWrapperCallFunctionArgs(
      {required PyModuleWrapper that,
      required String funcName,
      required List<PyArgument> args}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
            that, serializer);
        sse_encode_String(funcName, serializer);
        sse_encode_list_py_argument(args, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyModuleWrapperCallFunctionArgsConstMeta,
      argValues: [that, funcName, args],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyModuleWrapperCallFunctionArgsConstMeta =>
      const TaskConstMeta(
        debugName: "PyModuleWrapper_call_function_args",
        argNames: ["that", "funcName", "args"],
      );

  @override
  PyModuleWrapper crateApiPythonPyModuleWrapperImportModule(
      {required String moduleName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(moduleName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyModuleWrapperImportModuleConstMeta,
      argValues: [moduleName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyModuleWrapperImportModuleConstMeta =>
      const TaskConstMeta(
        debugName: "PyModuleWrapper_import_module",
        argNames: ["moduleName"],
      );

  @override
  bool crateApiPythonPyObjectWrapperAsBool({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsBoolConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsBoolConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_bool",
        argNames: ["that"],
      );

  @override
  double crateApiPythonPyObjectWrapperAsFloat({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsFloatConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsFloatConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_float",
        argNames: ["that"],
      );

  @override
  PlatformInt64 crateApiPythonPyObjectWrapperAsInt(
      {required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_i_64,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsIntConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsIntConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_int",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiPythonPyObjectWrapperAsListString(
      {required PyObjectWrapper that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsListStringConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsListStringConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_list_string",
        argNames: ["that"],
      );

  @override
  String crateApiPythonPyObjectWrapperAsRepr({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsReprConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsReprConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_repr",
        argNames: ["that"],
      );

  @override
  String crateApiPythonPyObjectWrapperAsStr({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperAsStrConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperAsStrConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_as_str",
        argNames: ["that"],
      );

  @override
  Future<PyObjectWrapper> crateApiPythonPyObjectWrapperCall(
      {required PyObjectWrapper that, required List<PyArgument> args}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_list_py_argument(args, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperCallConstMeta,
      argValues: [that, args],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperCallConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_call",
        argNames: ["that", "args"],
      );

  @override
  Future<PyObjectWrapper> crateApiPythonPyObjectWrapperCallMethod(
      {required PyObjectWrapper that,
      required String methodName,
      required List<PyArgument> args}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_String(methodName, serializer);
        sse_encode_list_py_argument(args, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperCallMethodConstMeta,
      argValues: [that, methodName, args],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperCallMethodConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_call_method",
        argNames: ["that", "methodName", "args"],
      );

  @override
  PyObjectWrapper crateApiPythonPyObjectWrapperGetItem(
      {required PyObjectWrapper that, required PyArgument key}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_box_autoadd_py_argument(key, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperGetItemConstMeta,
      argValues: [that, key],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperGetItemConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_get_item",
        argNames: ["that", "key"],
      );

  @override
  PyObjectWrapper crateApiPythonPyObjectWrapperGetattr(
      {required PyObjectWrapper that, required String attrName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_String(attrName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperGetattrConstMeta,
      argValues: [that, attrName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperGetattrConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_getattr",
        argNames: ["that", "attrName"],
      );

  @override
  bool crateApiPythonPyObjectWrapperHasattr(
      {required PyObjectWrapper that, required String attrName}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_String(attrName, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperHasattrConstMeta,
      argValues: [that, attrName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperHasattrConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_hasattr",
        argNames: ["that", "attrName"],
      );

  @override
  bool crateApiPythonPyObjectWrapperIsCallable(
      {required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperIsCallableConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperIsCallableConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_is_callable",
        argNames: ["that"],
      );

  @override
  bool crateApiPythonPyObjectWrapperIsEmpty({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_is_empty",
        argNames: ["that"],
      );

  @override
  bool crateApiPythonPyObjectWrapperIsNone({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperIsNoneConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperIsNoneConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_is_none",
        argNames: ["that"],
      );

  @override
  BigInt crateApiPythonPyObjectWrapperLen({required PyObjectWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_usize,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperLenConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperLenConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_len",
        argNames: ["that"],
      );

  @override
  void crateApiPythonPyObjectWrapperSetItem(
      {required PyObjectWrapper that,
      required PyArgument key,
      required PyArgument value}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_box_autoadd_py_argument(key, serializer);
        sse_encode_box_autoadd_py_argument(value, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperSetItemConstMeta,
      argValues: [that, key, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperSetItemConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_set_item",
        argNames: ["that", "key", "value"],
      );

  @override
  void crateApiPythonPyObjectWrapperSetattr(
      {required PyObjectWrapper that,
      required String attrName,
      required PyArgument value}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
            that, serializer);
        sse_encode_String(attrName, serializer);
        sse_encode_box_autoadd_py_argument(value, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPyObjectWrapperSetattrConstMeta,
      argValues: [that, attrName, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPyObjectWrapperSetattrConstMeta =>
      const TaskConstMeta(
        debugName: "PyObjectWrapper_setattr",
        argNames: ["that", "attrName", "value"],
      );

  @override
  void crateApiPythonInitPyEnv(
      {required String pythonHome,
      required String libPath,
      required String sitePackages}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(pythonHome, serializer);
        sse_encode_String(libPath, serializer);
        sse_encode_String(sitePackages, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonInitPyEnvConstMeta,
      argValues: [pythonHome, libPath, sitePackages],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonInitPyEnvConstMeta => const TaskConstMeta(
        debugName: "init_py_env",
        argNames: ["pythonHome", "libPath", "sitePackages"],
      );

  @override
  Future<String> crateApiPythonPythonUtilityEval(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals,
      required List<String> imports}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        sse_encode_opt_list_record_string_py_argument(globals, serializer);
        sse_encode_opt_list_record_string_py_argument(locals, serializer);
        sse_encode_list_String(imports, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilityEvalConstMeta,
      argValues: [code, globals, locals, imports],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilityEvalConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_eval",
        argNames: ["code", "globals", "locals", "imports"],
      );

  @override
  Future<PyObjectWrapper> crateApiPythonPythonUtilityEvalAsObject(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        sse_encode_opt_list_record_string_py_argument(globals, serializer);
        sse_encode_opt_list_record_string_py_argument(locals, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilityEvalAsObjectConstMeta,
      argValues: [code, globals, locals],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilityEvalAsObjectConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_eval_as_object",
        argNames: ["code", "globals", "locals"],
      );

  @override
  Future<void> crateApiPythonPythonUtilityExecute(
      {required String code,
      List<(String, PyArgument)>? globals,
      List<(String, PyArgument)>? locals}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(code, serializer);
        sse_encode_opt_list_record_string_py_argument(globals, serializer);
        sse_encode_opt_list_record_string_py_argument(locals, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilityExecuteConstMeta,
      argValues: [code, globals, locals],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilityExecuteConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_execute",
        argNames: ["code", "globals", "locals"],
      );

  @override
  Future<String> crateApiPythonPythonUtilityGetModuleAttr(
      {required String moduleName, required String attrName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(moduleName, serializer);
        sse_encode_String(attrName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilityGetModuleAttrConstMeta,
      argValues: [moduleName, attrName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilityGetModuleAttrConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_get_module_attr",
        argNames: ["moduleName", "attrName"],
      );

  @override
  Future<void> crateApiPythonPythonUtilityRunFile({required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilityRunFileConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilityRunFileConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_run_file",
        argNames: ["filePath"],
      );

  @override
  Future<void> crateApiPythonPythonUtilitySetModuleAttr(
      {required String moduleName,
      required String attrName,
      required PyArgument value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(moduleName, serializer);
        sse_encode_String(attrName, serializer);
        sse_encode_box_autoadd_py_argument(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPythonPythonUtilitySetModuleAttrConstMeta,
      argValues: [moduleName, attrName, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPythonPythonUtilitySetModuleAttrConstMeta =>
      const TaskConstMeta(
        debugName: "python_utility_set_module_attr",
        argNames: ["moduleName", "attrName", "value"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_PyModuleWrapper => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_PyModuleWrapper => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_PyObjectWrapper => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_PyObjectWrapper => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  PyModuleWrapper
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PyObjectWrapper
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PyModuleWrapper
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PyObjectWrapper
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PyModuleWrapper
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  PyObjectWrapper
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PyArgument dco_decode_box_autoadd_py_argument(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_py_argument(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<PyArgument> dco_decode_list_py_argument(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_py_argument).toList();
  }

  @protected
  List<(String, PyArgument)> dco_decode_list_record_string_py_argument(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_py_argument)
        .toList();
  }

  @protected
  List<(String, PyArgument)>? dco_decode_opt_list_record_string_py_argument(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_record_string_py_argument(raw);
  }

  @protected
  PyArgument dco_decode_py_argument(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PyArgument_Str(
          dco_decode_String(raw[1]),
        );
      case 1:
        return PyArgument_Int(
          dco_decode_i_64(raw[1]),
        );
      case 2:
        return PyArgument_Float(
          dco_decode_f_64(raw[1]),
        );
      case 3:
        return PyArgument_Bool(
          dco_decode_bool(raw[1]),
        );
      case 4:
        return PyArgument_ListStr(
          dco_decode_list_String(raw[1]),
        );
      case 5:
        return PyArgument_ListInt(
          dco_decode_list_prim_i_64_strict(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PythonUtility dco_decode_python_utility(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return PythonUtility();
  }

  @protected
  (String, PyArgument) dco_decode_record_string_py_argument(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_py_argument(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  PyModuleWrapper
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PyObjectWrapper
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PyModuleWrapper
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PyObjectWrapper
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PyModuleWrapper
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyModuleWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  PyObjectWrapper
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PyObjectWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PyArgument sse_decode_box_autoadd_py_argument(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_py_argument(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<PyArgument> sse_decode_list_py_argument(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PyArgument>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_py_argument(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, PyArgument)> sse_decode_list_record_string_py_argument(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, PyArgument)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_py_argument(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, PyArgument)>? sse_decode_opt_list_record_string_py_argument(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_record_string_py_argument(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PyArgument sse_decode_py_argument(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return PyArgument_Str(var_field0);
      case 1:
        var var_field0 = sse_decode_i_64(deserializer);
        return PyArgument_Int(var_field0);
      case 2:
        var var_field0 = sse_decode_f_64(deserializer);
        return PyArgument_Float(var_field0);
      case 3:
        var var_field0 = sse_decode_bool(deserializer);
        return PyArgument_Bool(var_field0);
      case 4:
        var var_field0 = sse_decode_list_String(deserializer);
        return PyArgument_ListStr(var_field0);
      case 5:
        var var_field0 = sse_decode_list_prim_i_64_strict(deserializer);
        return PyArgument_ListInt(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PythonUtility sse_decode_python_utility(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PythonUtility();
  }

  @protected
  (String, PyArgument) sse_decode_record_string_py_argument(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_py_argument(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          PyModuleWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyModuleWrapperImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          PyObjectWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyObjectWrapperImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          PyModuleWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyModuleWrapperImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          PyObjectWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyObjectWrapperImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyModuleWrapper(
          PyModuleWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyModuleWrapperImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPyObjectWrapper(
          PyObjectWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as PyObjectWrapperImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_py_argument(
      PyArgument self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_py_argument(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_py_argument(
      List<PyArgument> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_py_argument(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_py_argument(
      List<(String, PyArgument)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_py_argument(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_record_string_py_argument(
      List<(String, PyArgument)>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_record_string_py_argument(self, serializer);
    }
  }

  @protected
  void sse_encode_py_argument(PyArgument self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PyArgument_Str(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case PyArgument_Int(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(field0, serializer);
      case PyArgument_Float(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_f_64(field0, serializer);
      case PyArgument_Bool(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(field0, serializer);
      case PyArgument_ListStr(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_list_String(field0, serializer);
      case PyArgument_ListInt(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_list_prim_i_64_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_python_utility(PythonUtility self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_record_string_py_argument(
      (String, PyArgument) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_py_argument(self.$2, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class PyModuleWrapperImpl extends RustOpaque implements PyModuleWrapper {
  // Not to be used by end users
  PyModuleWrapperImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PyModuleWrapperImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PyModuleWrapper,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PyModuleWrapper,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PyModuleWrapperPtr,
  );

  String asStr() => RustLib.instance.api.crateApiPythonPyModuleWrapperAsStr(
        that: this,
      );

  String callFunction({required String funcName}) =>
      RustLib.instance.api.crateApiPythonPyModuleWrapperCallFunction(
          that: this, funcName: funcName);

  String callFunctionArgs(
          {required String funcName, required List<PyArgument> args}) =>
      RustLib.instance.api.crateApiPythonPyModuleWrapperCallFunctionArgs(
          that: this, funcName: funcName, args: args);
}

@sealed
class PyObjectWrapperImpl extends RustOpaque implements PyObjectWrapper {
  // Not to be used by end users
  PyObjectWrapperImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PyObjectWrapperImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_PyObjectWrapper,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_PyObjectWrapper,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_PyObjectWrapperPtr,
  );

  /// 尝试转换成 bool
  bool asBool() => RustLib.instance.api.crateApiPythonPyObjectWrapperAsBool(
        that: this,
      );

  /// 尝试转换成 f64
  double asFloat() => RustLib.instance.api.crateApiPythonPyObjectWrapperAsFloat(
        that: this,
      );

  /// 尝试转换成 i64
  PlatformInt64 asInt() =>
      RustLib.instance.api.crateApiPythonPyObjectWrapperAsInt(
        that: this,
      );

  /// 尝试将 List 转换为 Vec<String> (用于 Dart)
  Future<List<String>> asListString() =>
      RustLib.instance.api.crateApiPythonPyObjectWrapperAsListString(
        that: this,
      );

  /// 对应 Python: repr(self)
  String asRepr() => RustLib.instance.api.crateApiPythonPyObjectWrapperAsRepr(
        that: this,
      );

  /// 对应 Python: str(self)
  String asStr() => RustLib.instance.api.crateApiPythonPyObjectWrapperAsStr(
        that: this,
      );

  /// 调用对象 (如果它是函数或类)
  /// Python: self(*args)
  Future<PyObjectWrapper> call({required List<PyArgument> args}) =>
      RustLib.instance.api
          .crateApiPythonPyObjectWrapperCall(that: this, args: args);

  /// 调用对象的方法
  /// Python: self.method_name(*args)
  Future<PyObjectWrapper> callMethod(
          {required String methodName, required List<PyArgument> args}) =>
      RustLib.instance.api.crateApiPythonPyObjectWrapperCallMethod(
          that: this, methodName: methodName, args: args);

  /// 字典/列表获取项
  /// Python: self[key]
  PyObjectWrapper getItem({required PyArgument key}) => RustLib.instance.api
      .crateApiPythonPyObjectWrapperGetItem(that: this, key: key);

  /// 获取属性，返回新的对象句柄
  /// Python: self.attr_name
  PyObjectWrapper getattr({required String attrName}) => RustLib.instance.api
      .crateApiPythonPyObjectWrapperGetattr(that: this, attrName: attrName);

  /// 检查属性是否存在
  /// Python: hasattr(self, attr_name)
  bool hasattr({required String attrName}) => RustLib.instance.api
      .crateApiPythonPyObjectWrapperHasattr(that: this, attrName: attrName);

  bool isCallable() =>
      RustLib.instance.api.crateApiPythonPyObjectWrapperIsCallable(
        that: this,
      );

  /// 检查是否为空
  bool isEmpty() => RustLib.instance.api.crateApiPythonPyObjectWrapperIsEmpty(
        that: this,
      );

  bool isNone() => RustLib.instance.api.crateApiPythonPyObjectWrapperIsNone(
        that: this,
      );

  /// 获取长度 (用于 List, Dict, Str, Set 等)
  /// Python: len(self)
  BigInt len() => RustLib.instance.api.crateApiPythonPyObjectWrapperLen(
        that: this,
      );

  /// 字典/列表设置项
  /// Python: self[key] = value
  void setItem({required PyArgument key, required PyArgument value}) => RustLib
      .instance.api
      .crateApiPythonPyObjectWrapperSetItem(that: this, key: key, value: value);

  /// 设置属性
  /// Python: self.attr_name = value
  void setattr({required String attrName, required PyArgument value}) =>
      RustLib.instance.api.crateApiPythonPyObjectWrapperSetattr(
          that: this, attrName: attrName, value: value);
}
